services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
      - ./spark-events:/opt/spark/spark-events
    networks:
      - spark-network

  spark-history:
    image: apache/spark:3.5.0
    container_name: spark-history
    hostname: spark-history
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/spark-events
    ports:
      - "18080:18080"
    volumes:
      - ./spark-events:/opt/spark/spark-events
    depends_on:
      - spark-master
    networks:
      - spark-network

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
      - "7080:7080"
      - "7081:7081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_DRIVER_HOST=191.52.98.23
      - SPARK_DRIVER_BIND_ADDRESS=0.0.0.0
      - SPARK_DRIVER_PORT=7080
      - SPARK_BLOCK_MANAGER_PORT=7081
    volumes:
      - ./notebooks:/opt/spark/work-dir
      - ./spark-data:/opt/spark-data
      - ./spark-events:/opt/spark/spark-events
    networks:
      - spark-network
    depends_on:
      - spark-master

networks:
  spark-network:
    driver: bridge
