# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookstore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bookstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookstore.proto\x12\tbookstore\"\x1e\n\rSearchRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"$\n\rLookupRequest\x12\x13\n\x0bitem_number\x18\x01 \x01(\x05\"!\n\nBuyRequest\x12\x13\n\x0bitem_number\x18\x01 \x01(\x05\"K\n\x08\x42ookInfo\x12\x13\n\x0bitem_number\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\r\n\x05stock\x18\x04 \x01(\x05\"4\n\x0eSearchResponse\x12\"\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x13.bookstore.BookInfo\"D\n\x0eLookupResponse\x12!\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x13.bookstore.BookInfo\x12\x0f\n\x07success\x18\x02 \x01(\x08\"/\n\x0b\x42uyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc5\x01\n\tBookstore\x12?\n\x06Search\x12\x18.bookstore.SearchRequest\x1a\x19.bookstore.SearchResponse\"\x00\x12?\n\x06Lookup\x12\x18.bookstore.LookupRequest\x1a\x19.bookstore.LookupResponse\"\x00\x12\x36\n\x03\x42uy\x12\x15.bookstore.BuyRequest\x1a\x16.bookstore.BuyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=60
  _globals['_LOOKUPREQUEST']._serialized_start=62
  _globals['_LOOKUPREQUEST']._serialized_end=98
  _globals['_BUYREQUEST']._serialized_start=100
  _globals['_BUYREQUEST']._serialized_end=133
  _globals['_BOOKINFO']._serialized_start=135
  _globals['_BOOKINFO']._serialized_end=210
  _globals['_SEARCHRESPONSE']._serialized_start=212
  _globals['_SEARCHRESPONSE']._serialized_end=264
  _globals['_LOOKUPRESPONSE']._serialized_start=266
  _globals['_LOOKUPRESPONSE']._serialized_end=334
  _globals['_BUYRESPONSE']._serialized_start=336
  _globals['_BUYRESPONSE']._serialized_end=383
  _globals['_BOOKSTORE']._serialized_start=386
  _globals['_BOOKSTORE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
