# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03\x61rg\x18\x01 \x01(\t\"K\n\x08\x42ookInfo\x12\x13\n\x0bitem_number\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\r\n\x05stock\x18\x04 \x01(\x05\"B\n\rQueryResponse\x12 \n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x11.catalog.BookInfo\x12\x0f\n\x07success\x18\x02 \x01(\x08\"1\n\rUpdateRequest\x12\x13\n\x0bitem_number\x18\x01 \x01(\x05\x12\x0b\n\x03qty\x18\x02 \x01(\x05\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x80\x01\n\x07\x43\x61talog\x12\x38\n\x05Query\x12\x15.catalog.QueryRequest\x1a\x16.catalog.QueryResponse\"\x00\x12;\n\x06Update\x12\x16.catalog.UpdateRequest\x1a\x17.catalog.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=26
  _globals['_QUERYREQUEST']._serialized_end=53
  _globals['_BOOKINFO']._serialized_start=55
  _globals['_BOOKINFO']._serialized_end=130
  _globals['_QUERYRESPONSE']._serialized_start=132
  _globals['_QUERYRESPONSE']._serialized_end=198
  _globals['_UPDATEREQUEST']._serialized_start=200
  _globals['_UPDATEREQUEST']._serialized_end=249
  _globals['_UPDATERESPONSE']._serialized_start=251
  _globals['_UPDATERESPONSE']._serialized_end=301
  _globals['_CATALOG']._serialized_start=304
  _globals['_CATALOG']._serialized_end=432
# @@protoc_insertion_point(module_scope)
