# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sdwb_pb2 as sdwb__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sdwb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoNomesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarQuadro = channel.unary_unary(
                '/sdwb.ServicoNomes/RegistrarQuadro',
                request_serializer=sdwb__pb2.InfoQuadro.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.ListarQuadros = channel.unary_unary(
                '/sdwb.ServicoNomes/ListarQuadros',
                request_serializer=sdwb__pb2.Vazio.SerializeToString,
                response_deserializer=sdwb__pb2.ListaQuadros.FromString,
                _registered_method=True)
        self.AtualizarQuadro = channel.unary_unary(
                '/sdwb.ServicoNomes/AtualizarQuadro',
                request_serializer=sdwb__pb2.InfoQuadro.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.RemoverQuadro = channel.unary_unary(
                '/sdwb.ServicoNomes/RemoverQuadro',
                request_serializer=sdwb__pb2.NomeQuadro.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)


class ServicoNomesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarQuadro(self, request, context):
        """Coordenador registra um novo quadro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarQuadros(self, request, context):
        """Cliente lista os quadros disponiveis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarQuadro(self, request, context):
        """Novo coordenador (apos eleicao) atualiza o endereco do quadro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverQuadro(self, request, context):
        """Quadro encerrado (coordenador sozinho saiu/caiu).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoNomesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarQuadro': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarQuadro,
                    request_deserializer=sdwb__pb2.InfoQuadro.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'ListarQuadros': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarQuadros,
                    request_deserializer=sdwb__pb2.Vazio.FromString,
                    response_serializer=sdwb__pb2.ListaQuadros.SerializeToString,
            ),
            'AtualizarQuadro': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarQuadro,
                    request_deserializer=sdwb__pb2.InfoQuadro.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'RemoverQuadro': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverQuadro,
                    request_deserializer=sdwb__pb2.NomeQuadro.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.ServicoNomes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdwb.ServicoNomes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoNomes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarQuadro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ServicoNomes/RegistrarQuadro',
            sdwb__pb2.InfoQuadro.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarQuadros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ServicoNomes/ListarQuadros',
            sdwb__pb2.Vazio.SerializeToString,
            sdwb__pb2.ListaQuadros.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarQuadro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ServicoNomes/AtualizarQuadro',
            sdwb__pb2.InfoQuadro.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverQuadro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ServicoNomes/RemoverQuadro',
            sdwb__pb2.NomeQuadro.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordenadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_stream(
                '/sdwb.Coordenador/Join',
                request_serializer=sdwb__pb2.PedidoJoin.SerializeToString,
                response_deserializer=sdwb__pb2.Evento.FromString,
                _registered_method=True)
        self.EnviarOperacao = channel.unary_unary(
                '/sdwb.Coordenador/EnviarOperacao',
                request_serializer=sdwb__pb2.Operacao.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.Selecionar = channel.unary_unary(
                '/sdwb.Coordenador/Selecionar',
                request_serializer=sdwb__pb2.PedidoLock.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.Liberar = channel.unary_unary(
                '/sdwb.Coordenador/Liberar',
                request_serializer=sdwb__pb2.PedidoLock.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/sdwb.Coordenador/Heartbeat',
                request_serializer=sdwb__pb2.InfoMembro.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.Sair = channel.unary_unary(
                '/sdwb.Coordenador/Sair',
                request_serializer=sdwb__pb2.InfoMembro.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)


class CoordenadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request, context):
        """Cliente chama uma vez; recebe ESTADO_INICIAL e a stream fica aberta
        para o Coordenador empurrar cada evento novo (broadcast).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarOperacao(self, request, context):
        """Desenhar / colorir / remover. Coordenador atribui sequencia e difunde.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Selecionar(self, request, context):
        """Exclusao mutua por objeto.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Liberar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat centralizado: cliente -> coordenador a cada T segundos.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sair(self, request, context):
        """Saida graciosa (mensagem explicita), distinta de queda por timeout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordenadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_stream_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=sdwb__pb2.PedidoJoin.FromString,
                    response_serializer=sdwb__pb2.Evento.SerializeToString,
            ),
            'EnviarOperacao': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarOperacao,
                    request_deserializer=sdwb__pb2.Operacao.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'Selecionar': grpc.unary_unary_rpc_method_handler(
                    servicer.Selecionar,
                    request_deserializer=sdwb__pb2.PedidoLock.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'Liberar': grpc.unary_unary_rpc_method_handler(
                    servicer.Liberar,
                    request_deserializer=sdwb__pb2.PedidoLock.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=sdwb__pb2.InfoMembro.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'Sair': grpc.unary_unary_rpc_method_handler(
                    servicer.Sair,
                    request_deserializer=sdwb__pb2.InfoMembro.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.Coordenador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdwb.Coordenador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordenador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sdwb.Coordenador/Join',
            sdwb__pb2.PedidoJoin.SerializeToString,
            sdwb__pb2.Evento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarOperacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.Coordenador/EnviarOperacao',
            sdwb__pb2.Operacao.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Selecionar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.Coordenador/Selecionar',
            sdwb__pb2.PedidoLock.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Liberar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.Coordenador/Liberar',
            sdwb__pb2.PedidoLock.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.Coordenador/Heartbeat',
            sdwb__pb2.InfoMembro.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.Coordenador/Sair',
            sdwb__pb2.InfoMembro.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Eleicao = channel.unary_unary(
                '/sdwb.No/Eleicao',
                request_serializer=sdwb__pb2.PedidoEleicao.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)
        self.AnunciarCoordenador = channel.unary_unary(
                '/sdwb.No/AnunciarCoordenador',
                request_serializer=sdwb__pb2.AnuncioCoordenador.SerializeToString,
                response_deserializer=sdwb__pb2.Resposta.FromString,
                _registered_method=True)


class NoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Eleicao(self, request, context):
        """Valentao: no manda Eleicao a IDs maiores; quem responde ok assume a frente.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnunciarCoordenador(self, request, context):
        """Vencedor difunde que e o novo coordenador.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Eleicao': grpc.unary_unary_rpc_method_handler(
                    servicer.Eleicao,
                    request_deserializer=sdwb__pb2.PedidoEleicao.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
            'AnunciarCoordenador': grpc.unary_unary_rpc_method_handler(
                    servicer.AnunciarCoordenador,
                    request_deserializer=sdwb__pb2.AnuncioCoordenador.FromString,
                    response_serializer=sdwb__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.No', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdwb.No', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class No(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Eleicao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.No/Eleicao',
            sdwb__pb2.PedidoEleicao.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnunciarCoordenador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.No/AnunciarCoordenador',
            sdwb__pb2.AnuncioCoordenador.SerializeToString,
            sdwb__pb2.Resposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
