# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import minibib_pb2 as minibib__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in minibib_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoCatalogoStub(object):
    """─── Serviços ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultaPorTopico = channel.unary_unary(
                '/minibib.ServicoCatalogo/ConsultaPorTopico',
                request_serializer=minibib__pb2.ConsultaPorTopicoRequest.SerializeToString,
                response_deserializer=minibib__pb2.ConsultaPorTopicoReply.FromString,
                _registered_method=True)
        self.ConsultaPorItem = channel.unary_unary(
                '/minibib.ServicoCatalogo/ConsultaPorItem',
                request_serializer=minibib__pb2.ConsultaPorItemRequest.SerializeToString,
                response_deserializer=minibib__pb2.InfoLivro.FromString,
                _registered_method=True)
        self.Atualizar = channel.unary_unary(
                '/minibib.ServicoCatalogo/Atualizar',
                request_serializer=minibib__pb2.AtualizacaoRequest.SerializeToString,
                response_deserializer=minibib__pb2.AtualizacaoReply.FromString,
                _registered_method=True)


class ServicoCatalogoServicer(object):
    """─── Serviços ───

    """

    def ConsultaPorTopico(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultaPorItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Atualizar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoCatalogoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultaPorTopico': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultaPorTopico,
                    request_deserializer=minibib__pb2.ConsultaPorTopicoRequest.FromString,
                    response_serializer=minibib__pb2.ConsultaPorTopicoReply.SerializeToString,
            ),
            'ConsultaPorItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultaPorItem,
                    request_deserializer=minibib__pb2.ConsultaPorItemRequest.FromString,
                    response_serializer=minibib__pb2.InfoLivro.SerializeToString,
            ),
            'Atualizar': grpc.unary_unary_rpc_method_handler(
                    servicer.Atualizar,
                    request_deserializer=minibib__pb2.AtualizacaoRequest.FromString,
                    response_serializer=minibib__pb2.AtualizacaoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minibib.ServicoCatalogo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minibib.ServicoCatalogo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoCatalogo(object):
    """─── Serviços ───

    """

    @staticmethod
    def ConsultaPorTopico(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoCatalogo/ConsultaPorTopico',
            minibib__pb2.ConsultaPorTopicoRequest.SerializeToString,
            minibib__pb2.ConsultaPorTopicoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultaPorItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoCatalogo/ConsultaPorItem',
            minibib__pb2.ConsultaPorItemRequest.SerializeToString,
            minibib__pb2.InfoLivro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Atualizar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoCatalogo/Atualizar',
            minibib__pb2.AtualizacaoRequest.SerializeToString,
            minibib__pb2.AtualizacaoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServicoPedidosStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Comprar = channel.unary_unary(
                '/minibib.ServicoPedidos/Comprar',
                request_serializer=minibib__pb2.CompraRequest.SerializeToString,
                response_deserializer=minibib__pb2.CompraReply.FromString,
                _registered_method=True)


class ServicoPedidosServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Comprar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoPedidosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Comprar': grpc.unary_unary_rpc_method_handler(
                    servicer.Comprar,
                    request_deserializer=minibib__pb2.CompraRequest.FromString,
                    response_serializer=minibib__pb2.CompraReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minibib.ServicoPedidos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minibib.ServicoPedidos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoPedidos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Comprar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoPedidos/Comprar',
            minibib__pb2.CompraRequest.SerializeToString,
            minibib__pb2.CompraReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServicoFrontEndStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Buscar = channel.unary_unary(
                '/minibib.ServicoFrontEnd/Buscar',
                request_serializer=minibib__pb2.BuscaRequest.SerializeToString,
                response_deserializer=minibib__pb2.BuscaReply.FromString,
                _registered_method=True)
        self.Consultar = channel.unary_unary(
                '/minibib.ServicoFrontEnd/Consultar',
                request_serializer=minibib__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=minibib__pb2.InfoLivro.FromString,
                _registered_method=True)
        self.Comprar = channel.unary_unary(
                '/minibib.ServicoFrontEnd/Comprar',
                request_serializer=minibib__pb2.CompraRequest.SerializeToString,
                response_deserializer=minibib__pb2.CompraReply.FromString,
                _registered_method=True)


class ServicoFrontEndServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Buscar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consultar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Comprar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoFrontEndServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Buscar': grpc.unary_unary_rpc_method_handler(
                    servicer.Buscar,
                    request_deserializer=minibib__pb2.BuscaRequest.FromString,
                    response_serializer=minibib__pb2.BuscaReply.SerializeToString,
            ),
            'Consultar': grpc.unary_unary_rpc_method_handler(
                    servicer.Consultar,
                    request_deserializer=minibib__pb2.ConsultaRequest.FromString,
                    response_serializer=minibib__pb2.InfoLivro.SerializeToString,
            ),
            'Comprar': grpc.unary_unary_rpc_method_handler(
                    servicer.Comprar,
                    request_deserializer=minibib__pb2.CompraRequest.FromString,
                    response_serializer=minibib__pb2.CompraReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minibib.ServicoFrontEnd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minibib.ServicoFrontEnd', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoFrontEnd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Buscar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoFrontEnd/Buscar',
            minibib__pb2.BuscaRequest.SerializeToString,
            minibib__pb2.BuscaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consultar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoFrontEnd/Consultar',
            minibib__pb2.ConsultaRequest.SerializeToString,
            minibib__pb2.InfoLivro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Comprar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minibib.ServicoFrontEnd/Comprar',
            minibib__pb2.CompraRequest.SerializeToString,
            minibib__pb2.CompraReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
