# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: minibib.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'minibib.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rminibib.proto\x12\x07minibib\"\x1e\n\x0c\x42uscaRequest\x12\x0e\n\x06topico\x18\x01 \x01(\t\"#\n\nBuscaReply\x12\x15\n\rnumeros_itens\x18\x01 \x03(\x05\"&\n\x0f\x43onsultaRequest\x12\x13\n\x0bnumero_item\x18\x01 \x01(\x05\"O\n\tInfoLivro\x12\x13\n\x0bnumero_item\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0e\n\x06topico\x18\x03 \x01(\t\x12\x0f\n\x07\x65stoque\x18\x04 \x01(\x05\"$\n\rCompraRequest\x12\x13\n\x0bnumero_item\x18\x01 \x01(\x05\"0\n\x0b\x43ompraReply\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"*\n\x18\x43onsultaPorTopicoRequest\x12\x0e\n\x06topico\x18\x01 \x01(\t\"/\n\x16\x43onsultaPorTopicoReply\x12\x15\n\rnumeros_itens\x18\x01 \x03(\x05\"-\n\x16\x43onsultaPorItemRequest\x12\x13\n\x0bnumero_item\x18\x01 \x01(\x05\"=\n\x12\x41tualizacaoRequest\x12\x13\n\x0bnumero_item\x18\x01 \x01(\x05\x12\x12\n\nquantidade\x18\x02 \x01(\x05\"5\n\x10\x41tualizacaoReply\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\xf7\x01\n\x0fServicoCatalogo\x12W\n\x11\x43onsultaPorTopico\x12!.minibib.ConsultaPorTopicoRequest\x1a\x1f.minibib.ConsultaPorTopicoReply\x12\x46\n\x0f\x43onsultaPorItem\x12\x1f.minibib.ConsultaPorItemRequest\x1a\x12.minibib.InfoLivro\x12\x43\n\tAtualizar\x12\x1b.minibib.AtualizacaoRequest\x1a\x19.minibib.AtualizacaoReply2I\n\x0eServicoPedidos\x12\x37\n\x07\x43omprar\x12\x16.minibib.CompraRequest\x1a\x14.minibib.CompraReply2\xbb\x01\n\x0fServicoFrontEnd\x12\x34\n\x06\x42uscar\x12\x15.minibib.BuscaRequest\x1a\x13.minibib.BuscaReply\x12\x39\n\tConsultar\x12\x18.minibib.ConsultaRequest\x1a\x12.minibib.InfoLivro\x12\x37\n\x07\x43omprar\x12\x16.minibib.CompraRequest\x1a\x14.minibib.CompraReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minibib_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSCAREQUEST']._serialized_start=26
  _globals['_BUSCAREQUEST']._serialized_end=56
  _globals['_BUSCAREPLY']._serialized_start=58
  _globals['_BUSCAREPLY']._serialized_end=93
  _globals['_CONSULTAREQUEST']._serialized_start=95
  _globals['_CONSULTAREQUEST']._serialized_end=133
  _globals['_INFOLIVRO']._serialized_start=135
  _globals['_INFOLIVRO']._serialized_end=214
  _globals['_COMPRAREQUEST']._serialized_start=216
  _globals['_COMPRAREQUEST']._serialized_end=252
  _globals['_COMPRAREPLY']._serialized_start=254
  _globals['_COMPRAREPLY']._serialized_end=302
  _globals['_CONSULTAPORTOPICOREQUEST']._serialized_start=304
  _globals['_CONSULTAPORTOPICOREQUEST']._serialized_end=346
  _globals['_CONSULTAPORTOPICOREPLY']._serialized_start=348
  _globals['_CONSULTAPORTOPICOREPLY']._serialized_end=395
  _globals['_CONSULTAPORITEMREQUEST']._serialized_start=397
  _globals['_CONSULTAPORITEMREQUEST']._serialized_end=442
  _globals['_ATUALIZACAOREQUEST']._serialized_start=444
  _globals['_ATUALIZACAOREQUEST']._serialized_end=505
  _globals['_ATUALIZACAOREPLY']._serialized_start=507
  _globals['_ATUALIZACAOREPLY']._serialized_end=560
  _globals['_SERVICOCATALOGO']._serialized_start=563
  _globals['_SERVICOCATALOGO']._serialized_end=810
  _globals['_SERVICOPEDIDOS']._serialized_start=812
  _globals['_SERVICOPEDIDOS']._serialized_end=885
  _globals['_SERVICOFRONTEND']._serialized_start=888
  _globals['_SERVICOFRONTEND']._serialized_end=1075
# @@protoc_insertion_point(module_scope)
